### PR TITLE
Fix: Reference component can break the page loading #164

### LINKED ISSUE #164: Reference component can break the page loading
One can easily break the page with the Reference component in yet [another way](https://github.com/headwirecom/peregrine-cms/issues/579).

# Steps to Reproduce
1. Add new page,
1. Add Reference component,
1. Point it to a different page,
1. Save everything,
1. Reload the page.

**Expected Result**: no big deal, system renders the page properly.
**Actual Result**: `loading: Home Test`:
reference_2
While before reload we simply have: 
reference_1

### PR DESCRIPTION
**Pull request by reggie7**
Fixes #164

### CODE REVIEW

File: core/src/main/java/com/themecleanflex/models/ReferenceModel.java [hunk 1]
```diff
@@ -609,14 +606,13 @@ private String generateReferenceJson() {
...
         Object val = map.get(key);
-        if(key.equals(name)) {
-          if(value.equals(val)) {
+        if(equals(key, name)) {
+          if(equals(value, val)) {
             return map;
           }
         }
-        if(key.equals("children") && val instanceof ArrayList) {
+        if("children".equals(key) && val instanceof ArrayList) {
```
Comment (flx-sta) [inline core/src/main/java/com/themecleanflex/models/ReferenceModel.java:614]: is there a reason why you use `equals(obj, other)` above but `String.equals(otherString)` here?

**Review by flx-sta — APPROVED** [review]
apart from my question LGTM 🚀

**Review by reusr1 — APPROVED** [review]
